site_name: C++程序员的Python入门
site_url: http://python.hackerphysics.com

theme:
    name: material
    logo: images/python.png
    favicon: images/python.png
    language: 'zh'
    features:
      - navigation.expand
      - navigation.top
      - navigation.tabs
      - search.suggest
      - toc.integrate
      - content.code.annotate
nav:
    - '前言': 'index.md'
    # - '编程语言漫谈': '0-programming-languages.md'
    - '基础知识': '1-python-fundamentals.md'
    - '函数': '2-python-function.md'
    - '类':  '3-python-class.md'
    - '模块': '4-python-module.md'
    - '科学计算': '5-python-numpy.md'
    - '实战': '6-python-applications.md'

markdown_extensions:
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js