site_name: Beginning Python for C++ Developers
site_url: http://python.hackerphysics.com

theme:
    name: mkdocs
    font:
      text: Roboto
      code: Roboto Mono
    features:
      - navigation.expand
      - navigation.tabs
      - search.suggest
      - toc.integrate

nav:
    - Home: index.md